### ISSUE TITLE
8 knobs synth and XORAND without MIDI

### ISSUE THREAD

**Issue by pirvcb** [tomcombriat/TES_8-knobs-synth#3]
Hi Thomas.
I toke a look to your really interesting works.
I would like ask you if you have old betas or test sketches about XORAND and 8 knobs synth that you can up.
I'd like try to get out juice without MIDI protocol but using knobs instead. Otherwise, i ask you to suggest me just the right direction to go in deep trough your projects looking to convert MIDI input to analog input.
Thank you!
Davide.
P.S. My Akay EWI is still there.... but i'm just going explore others things.

**Comment by tomcombriat** [comment]
Hi,

Unfortunately, I do not have such sketches… My goal was, from the start, to make synths with MIDI support. However, this can be easily modified by assigning the knobs to something else (pitch? velocity? etc…), and keep the "synthesis part" of the XORAND.

Otherwise, I could also suggest to have a look on other projects made with Mozzi. Lot of them are based on AVR chips, so you might need to adjust a few things (AVR outputs 8bits, whereas the BP outputs 10), but I remember that quite a few of them are realized with knobs control. The [gallery](https://sensorium.github.io/Mozzi/gallery/) of Mozzi can be a good start, but also popular websites of videos streaming. Most of these do share their code.

Hope it helps,

**Comment by pirvcb** [comment]
Thnak You!
